fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v6.1.0'
    'firewall':
      repo: 'git://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: 'v2.1.0'
  symlinks:
    'monit': "#{source_dir}"
